name: Hourly Retrieval and push to Public-files Repo

on:
  schedule:
    - cron: "35 15,17,20 * * *"  # once per day
  workflow_dispatch:

concurrency:
  group: main-jobs
  cancel-in-progress: false
  
jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the scraper
        run: python _retrieve_topanalysts.py --mode fast

      - name: Commit and push output
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *_top_analysts.csv
          git add *_top_analysts.html
          git add *latest_top_analysts.csv
          git add *latest_top_analysts.html
          git commit -m "Daily update $(date)" || echo "Nothing to commit"
          git push
      
      - name: Push to public repo
        env:
          PUBLIC_REPO_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # clone the public repo
          git clone https://x-access-token:${PUBLIC_REPO_TOKEN}@github.com/pockos56/Public-files.git public_repo
          cd public_repo

          # copy CSVs
          mkdir -p from-Stocks
          cp ../from-Stocks/* from-Stocks/

          # commit & push
          git add from-Stocks/*
          git commit -m "Daily update $(date +'%Y-%m-%d')" || echo "Nothing to commit"
          git push

